# Generated by Django 5.0.5 on 2024-05-07 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('cliente_id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=252)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='modeloEstado',
            fields=[
                ('estado_id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='modeloEtapa',
            fields=[
                ('etapa_id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('etapa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='modeloProspecto',
            fields=[
                ('modelo_id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=252)),
                ('email', models.CharField(max_length=252)),
                ('telefono', models.IntegerField()),
                ('sexo', models.CharField(max_length=32)),
                ('cliente_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArkTools.cliente')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArkTools.modeloestado')),
                ('etapa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArkTools.modeloetapa')),
            ],
        ),
    ]
